### PR TITLE
remove links to parents in schema

### PR DESCRIPTION
**Pull request by terinpw**

### CODE REVIEW

**Comment by jessex** [comment]
What's the context for this one?

**Comment by terinpw** [comment]
@jessex - we wanted to remove these because it's a bit of weird structure to have children point back to their parent entities; and we don't currently have any use case for this bidirectional link (unless you have one in mind). 

From talking with @zdg2102, we were planning on removing these early on, but never got around to it until now.

**Comment by jessex** [comment]
Thanks, @terinpw! So we added these in the beginning just because we thought the bidirectional link might eventually be useful, but a use case never materialized? I don't have a use case myself. We can add those links back in the future if the use case shows up.

**Comment by terinpw** [comment]
@jessex - I believe we originally created the links because they were present in the example (in SQL Alchemy docs) that we were referencing.

But yeah, it's easy enough to add back if we need.

**Pull request merged**
