### PR TITLE
Update license text

### LINKED ISSUE #151: Update license text
"A platform for tracking granular recidivism metrics in real time" is now too specific. It should read "A data platform for criminal justice measurement and improvement."

### PR DESCRIPTION
**Pull request by jjdressel11**
Updates top of license text to read "Recidiviz - a data platform for criminal justice reform" and changes copyright to 2019.

Closes #151

### CODE REVIEW

**Comment by colincadams** [comment]
This is great! To get travis to pass, you'll have to have one commit message that starts with "[skip validation]". We have a tool that runs and checks to make sure that if a particular file is changed then other particular file is changed (i.e. if the schema is changed, a database migration is created) and the license text changes are tripping it erroneously.

**Comment by colincadams** [comment]
One thing this brings up, but outside of the scope of this PR, is that once the repo is private and especially if any contributors have to sign a CLA, we could remove the licenses from the private repo and have copybara add them on export. That way we can't potentially miss files and makes license updates much simpler than today. @jessex, wdyt? If so I can file a bug for it

**Comment by jessex** [comment]
Good call out, @colincadams. Feel free to file that issue and we'll tackle it in the future.

And my bad for failing to mention the skip validation requirement, @jjdressel11. Just need to amend your commit message and force push back to your branch and the build should pass!

**Comment by colincadams** [comment]
file #1397

**Comment by jjdressel11** [comment]
Thanks for the help! Pushed a commit with that change.

**Pull request merged**
