### PR TITLE
Added script to generate fips.csv

### LINKED ISSUE #815: Add tool for generating fips.csv
@rasmi proposed 2 solutions to consider working off:

```
"""Generates a CSV file of FIPS codes and county names."""

import csv
import io

import requests

FIPS_URL = (
  'https://www2.census.gov/geo/docs/reference/codes/files/national_county.txt')
FIPS_FIELDS = [
  'state_abbrev', 'state_code', 'county_code', 'county_name', 'class_code']

fips_data = requests.get(FIPS_URL)
fips_csv = csv.DictReader(io.StringIO(fips_data.text), fieldnames=FIPS_FIELDS)
fips_list = list(fips_csv)

for county in fips_list:
  county['fips'] = county['state_code'] + county['county_code']
  del county['class_code']

with open('fips.csv', 'w') as csvfile:
  fieldnames = [
    'fips', 'state_abbrev', 'state_code', 'county_code', 'county_name']
  writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
  writer.writeheader()
  writer.writerows(fips_list)
```

```
"""Generates a CSV file of FIPS codes and county names."""

import pandas as pd

FIPS_URL = (
  'https://www2.census.gov/geo/docs/reference/codes/files/national_county.txt')
FIPS_FIELDS = [
  'state_abbrev', 'state_code', 'county_code', 'county_name', 'class_code']

FIPS_DTYPES = {field: str for field in FIPS_FIELDS}
fips_df = pd.read_csv(FIPS_URL, names=FIPS_FIELDS, dtype=FIPS_DTYPES)

fips_df['fips'] = fips_df['state_code'] + fips_df['county_code']

fips_df = fips_df.drop('class_code', axis='columns')

fips_df.to_csv('fips.csv', index=False)
```

### PR DESCRIPTION
**Pull request by rasmi**
Fixes #815.

### CODE REVIEW

**Comment by rasmi** [comment]
CSV diff is large because the script preserves 0-padding in FIPS codes (see #821).

**Comment by rasmi** [comment]
I noticed the original `fips.csv` has `<state code>,999,<State> Unknown` records which are missing in the script I wrote.

**Comment by zacharylawrence** [comment]
> I noticed the original `fips.csv` has `<state code>,999,<State> Unknown` records which are missing in the script I wrote.

@ohinds might have more thoughts on this, but I think it's nice to include in the case where a county in a PDF truely shouldn't be mapped to any value.

**Comment by zacharylawrence** [comment]
@rasmi Is this good to submit?

**Pull request merged**
