### PR TITLE
DataExtractor: create parent multi_key classes if none exist

### LINKED ISSUE #283: data extractor should not create completely empty objects
In applying the data extractor to UsNy, I ran into an issue where the NYS DOCCS site always has 4 table rows to hold charges, even if there are less than 4 charges. So the extractor happily creates empty charges for each of these blank rows. The extractor should check if no fields of an entity have been filled in, and refuse to return an entity in that case.

### LINKED ISSUE #366: DataExtractor not able to handle new scraper
@arian487 

Data extractor is failing in PR #329. 

```
    for hier_class in hierarchy:
            # If we are a multi key class instead of getting the most recent
            # object as a parent, we use the index of the value we found
            if hier_class in self.multi_key_classes:
>               parent = getattr(parent, hier_class)[val_index]
E               IndexError: list index out of range

recidiviz/ingest/extractor/data_extractor.py:237: IndexError
```
And if i comment the part of the key yaml file out (bonds), then it produces too many charges.

### PR DESCRIPTION
**Pull request by jamwalla**
The bug is caused by trying to attach bonds to charges before the charges are scraped.

close #283 
close #366

### CODE REVIEW

**Comment by jessex** [comment]
To test this, I'd suggest writing a unit test case with data from the source site mentioned in the original issue. What do you think?

**Comment by arian487** [comment]
At first glance I think it definitely fixes it, but definitely need to test it out.

**Comment by jamwalla** [comment]
We can fall back on the create/get_recent logic for single-key classes when the parent class hasn't been created. This also fixes #283.

**Comment by jamwalla** [comment]
Thanks Arian and Josh!

close #283 
close #366

**Pull request merged**
