### PR TITLE
Fixes bond and crime description for us_pa_greene

### PR DESCRIPTION
**Pull request by arian487**

### CODE REVIEW

**Comment by arian487** [comment]
I haven't been able to really duplicate that some people are simply not extracted from https://github.com/Recidiviz/recidiviz-data/issues/160

Can you send an example?

**Comment by jessex** [comment]
I sent you screenshots with the aforementioned issue I am seeing, @arian487. I think you've got 2 of the 4 bugs from #160 handled here, then there's the one I just documented for you, and then there's the list index error issue for offenses. Half-way there!

**Comment by arian487** [comment]
Ok found the issue, I believe its fixed now!

**Comment by jessex** [comment]
These issues all appear fixed locally, @arian487! Great work. The only remaining issue I am seeing now is that `Person.person_id` and `Person.us_pa_greene_person_id` are both None for all Persons scraped in Greene County. (It's possible that some of the None fields in Record should _not_ be None but I trust you've audited this already.) Do you expect the person id's to be filled?

**Comment by arian487** [comment]
Ah yea I had already fixed that, forgot to commit.  I've committed that fix as well.

**Comment by jessex** [comment]
Thanks! That did it. But I just ran into an additional error:
```
webapp2/_internal_error : could not convert string to float: ond Denied
Traceback (most recent call last):
  File "/Users/clementinejacoby/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/clementinejacoby/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/clementinejacoby/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/clementinejacoby/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/Users/clementinejacoby/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/clementinejacoby/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/Users/clementinejacoby/Documents/projects/recidiviz-data/recidiviz/utils/auth.py", line 110, in auth_and_call
    return func(request_handler, *args, **kwargs)
  File "/Users/clementinejacoby/Documents/projects/recidiviz-data/recidiviz/ingest/worker.py", line 90, in post
    result = scraper_task(params)
  File "/Users/clementinejacoby/Documents/projects/recidiviz-data/recidiviz/ingest/generic_scraper.py", line 140, in _generic_scrape
    record, old_record = self._populate_record(content, params, person)
  File "/Users/clementinejacoby/Documents/projects/recidiviz-data/recidiviz/ingest/generic_scraper.py", line 235, in _populate_record
    record.offense = self.get_offenses(content, params)
  File "/Users/clementinejacoby/Documents/projects/recidiviz-data/recidiviz/ingest/us_pa_greene/us_pa_greene_scraper.py", line 525, in get_offenses
    bond_str)
  File "/Users/clementinejacoby/Documents/projects/recidiviz-data/recidiviz/ingest/scraper_utils.py", line 259, in currency_to_float
    return float(currency[1:].replace(',', ''))
ValueError: could not convert string to float: ond Denied
```

Perhaps not coincidentally, I also found another instance of a Record with all None fields. I wonder if this happens, somehow, when there's a hiccup in scraping a particular person page? It is correlative from what I've seen, anecdotally. Can send more screenshots if helpful tomorrow.

**Comment by arian487** [comment]
To elaborate, we never want errors like this to break our execution and result in a failed scrape.  At google (and all my projects), everything is very protected against values that may be unknown and may change.  Its standard practice to wrap entire functions that are not pivotal to the execution of a job and rather than letting them fail, you alert on their failure and allow the execution to continue.  

The code we have right now in general doesn't do that, and us_pa_greene is a good example of unexpected output causing failures everywhere (entire people not scraped).

**Pull request merged**
